// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// The AATKit default distribution: core plus every ad network in the default
// set. It ships no binaries and no source of its own — the dependencies below
// are the whole package.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-Default",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-Default", targets: ["AATKit-Default"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-GoogleMobileAds.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-AppLovin.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-AppNexus.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-InMobi.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-Mintegral.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-PubNative.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-GraviteRTB.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-Tappx.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-Unity.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-Vungle.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-IronSource.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-Prebid.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-GooglePartnerBidding.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-MetaBidding.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-MolocoBidding.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-DigitalTurbineBidding.git", exact: "3.18.0-beta3"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-Default",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    .product(name: "AATKit-GoogleMobileAds", package: "AATKit-GoogleMobileAds"),
                    .product(name: "AATKit-AppLovin", package: "AATKit-AppLovin"),
                    .product(name: "AATKit-AppNexus", package: "AATKit-AppNexus"),
                    .product(name: "AATKit-InMobi", package: "AATKit-InMobi"),
                    .product(name: "AATKit-Mintegral", package: "AATKit-Mintegral"),
                    .product(name: "AATKit-PubNative", package: "AATKit-PubNative"),
                    .product(name: "AATKit-GraviteRTB", package: "AATKit-GraviteRTB"),
                    .product(name: "AATKit-Tappx", package: "AATKit-Tappx"),
                    .product(name: "AATKit-Unity", package: "AATKit-Unity"),
                    .product(name: "AATKit-Vungle", package: "AATKit-Vungle"),
                    .product(name: "AATKit-IronSource", package: "AATKit-IronSource"),
                    .product(name: "AATKit-Prebid", package: "AATKit-Prebid"),
                    .product(name: "AATKit-GooglePartnerBidding", package: "AATKit-GooglePartnerBidding"),
                    .product(name: "AATKit-MetaBidding", package: "AATKit-MetaBidding"),
                    .product(name: "AATKit-MolocoBidding", package: "AATKit-MolocoBidding"),
                    .product(name: "AATKit-DigitalTurbineBidding", package: "AATKit-DigitalTurbineBidding"),
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-Default"),

        // Mark: Binary Targets
    ]
)
